# Generated by Django 5.1.2 on 2024-10-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embedder", "0002_embed_image_delete_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="embed",
            name="embedding",
            field=models.TextField(),
        ),
    ]
