# Generated by Django 5.1.2 on 2024-10-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embedder", "0003_alter_embed_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="embed",
            name="organization",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
